packages:
  - apps/*
  - packages/*
  - services/*

ignoredBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - prisma
  - sharp
  - unrs-resolver

offline: false

storeDir: C:\Users\OJOWA\Documents\Farm Management System\.pnpm-store
