export enum CropStageType {
  PREPARATION = 'PREPARATION',
  PLANTING = 'PLANTING',
  GERMINATION = 'GERMINATION',
  GROWING = 'GROWING',
  FLOWERING = 'FLOWERING',
  FRUITING = 'FRUITING',
  HARVESTING = 'HARVESTING',
  POST_HARVEST = 'POST_HARVEST',
}
