export enum ReportTemplate {
  FINANCIAL_SUMMARY = 'FINANCIAL_SUMMARY',
  CROP_PRODUCTION = 'CROP_PRODUCTION',
  LIVESTOCK_HEALTH = 'LIVESTOCK_HEALTH',
  INVENTORY = 'INVENTORY',
  CUSTOM = 'CUSTOM',
}
