"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.livestockRouter = void 0;
const express_1 = require("express");
const livestock_controller_1 = require("./livestock.controller");
const express_2 = require("../../../../../packages/auth/src/express/index");
const router = (0, express_1.Router)();
const livestockController = new livestock_controller_1.LivestockController();
router.get('/livestock', (0, express_2.authMiddleware)({ permission: 'livestock.read' }), livestockController.getAllLivestock);
router.get('/livestock/:id', (0, express_2.authMiddleware)({ permission: 'livestock.read' }), livestockController.getLivestockById);
router.post('/livestock', (0, express_2.authMiddleware)({ roles: ['ORGANIZATION_OWNER', 'FARM_MANAGER', 'SUPERVISOR', 'VETERINARIAN', 'SUPER_ADMIN'], permission: 'livestock.write' }), livestockController.createLivestock);
router.put('/livestock/:id', (0, express_2.authMiddleware)({ roles: ['ORGANIZATION_OWNER', 'FARM_MANAGER', 'SUPERVISOR', 'VETERINARIAN', 'SUPER_ADMIN'], permission: 'livestock.write' }), livestockController.updateLivestock);
router.delete('/livestock/:id', (0, express_2.authMiddleware)({ roles: ['ORGANIZATION_OWNER', 'FARM_MANAGER', 'VETERINARIAN', 'SUPER_ADMIN'], permission: 'livestock.delete' }), livestockController.deleteLivestock);
exports.livestockRouter = router;
exports.default = router;
