"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.inventoryRouter = void 0;
const express_1 = require("express");
const inventory_controller_1 = require("./inventory.controller");
const express_2 = require("../../../../../packages/auth/src/express/index");
const router = (0, express_1.Router)();
const inventoryController = new inventory_controller_1.InventoryController();
router.get('/inventory', (0, express_2.authMiddleware)({ permission: 'inventory.read' }), inventoryController.getAllInventoryItems);
router.get('/inventory/:id', (0, express_2.authMiddleware)({ permission: 'inventory.read' }), inventoryController.getInventoryItemById);
router.post('/inventory', (0, express_2.authMiddleware)({ roles: ['ORGANIZATION_OWNER', 'FARM_MANAGER', 'SUPERVISOR', 'SUPER_ADMIN'], permission: 'inventory.write' }), inventoryController.createInventoryItem);
router.put('/inventory/:id', (0, express_2.authMiddleware)({ roles: ['ORGANIZATION_OWNER', 'FARM_MANAGER', 'SUPERVISOR', 'SUPER_ADMIN'], permission: 'inventory.write' }), inventoryController.updateInventoryItem);
router.delete('/inventory/:id', (0, express_2.authMiddleware)({ roles: ['ORGANIZATION_OWNER', 'FARM_MANAGER', 'SUPER_ADMIN'], permission: 'inventory.delete' }), inventoryController.deleteInventoryItem);
exports.inventoryRouter = router;
exports.default = router;
